version: '3.5'

services:
  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    networks:
      - testConcepts
    ports:
      - "5433:1433"

  calculatorapi:
    image: ${DOCKER_REGISTRY-}calculatorapi
    build:
      context: .
      dockerfile: Calculator.API/Dockerfile
    depends_on:
      - sqldata
    networks:
      - testConcepts

  publicapi:
    image: ${DOCKER_REGISTRY-}publicapi
    build:
      context: .
      dockerfile: PublicApi/Dockerfile
    depends_on:
      - calculatorapi
    networks:
      - testConcepts

networks:
  testConcepts:
    name: testConcepts
