version: '3.5'

services:
  seq:
    image: datalust/seq:latest

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    networks:
      - mainConcepts
    ports:
      - "5433:1433"

  calculatorapi:
    image: ${DOCKER_REGISTRY-}calculatorapi
    build:
      context: .
      dockerfile: Services/Calculator.API/Dockerfile
    depends_on:
      - sqldata
    networks:
      - mainConcepts

  publicapi:
    image: ${DOCKER_REGISTRY-}publicapi
    build:
      context: .
      dockerfile: Services/PublicApi/Dockerfile
    depends_on:
      - calculatorapi
    networks:
      - mainConcepts

networks:
  mainConcepts:
    name: mainConcepts
