version: '3.5'

services:
  seq:
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    volumes:
      - ./Docker/SEQ:/data

  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - ./Docker/SQL:/var/opt/mssql/data

  redis:
    ports:
      - "6379:6379"
    volumes:
      - ./Docker/Redis:/data

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./Docker/RabbitMQ:/var/lib/rabbitmq/mnesia

  ocelotgateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5555:80"

  calculatorapi:
    environment:
      - ConnectionString=${CalculatorConnection:-Server=sqldata;User ID=sa;Password=Pass@word;Database=Calculator;}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBusConnection=${CalculatorEventBusConnection:-rabbitmq}
    ports:
      - "5101:80"
      - "9101:443"
      - "5433"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  publicapi:
    environment:
      - ConnectionString=${RedisPublicApi:-redis}
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBusConnection=${PublicApiEventBusConnection:-rabbitmq}
    ports:
      - "5102:80"
      - "9102:443"
      - "6379"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro