version: '3.5'

services:
  seq:
    image: datalust/seq:latest
    networks:
      - mainConcepts

  sqldata:
    image: mcr.microsoft.com/mssql/server:2017-latest 
    networks:
      - mainConcepts
    ports:
      - "5433:1433"

  redis: 
    image: redis:alpine
    networks:
      - mainConcepts

  rabbitmq:
    image: rabbitmq:3-management-alpine
    networks:
      - mainConcepts
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitUser"
      RABBITMQ_DEFAULT_PASS: "rabbitPass"

  ocelotgateway:
    image: ${DOCKER_REGISTRY}ocelotgateway
    build:
      context: .
      dockerfile: Gateway/Ocelot.Api.Gateway/Dockerfile

  calculatorapi:
    image: ${DOCKER_REGISTRY-}calculatorapi
    build:
      context: .
      dockerfile: Services/Calculator.API/Dockerfile
    depends_on:
      - rabbitmq
      - sqldata
    networks:
      - mainConcepts

  publicapi:
    image: ${DOCKER_REGISTRY-}publicapi
    build:
      context: .
      dockerfile: Services/PublicApi/Dockerfile
    depends_on:
      - calculatorapi
      - rabbitmq
      - redis
    networks:
      - mainConcepts

networks:
  mainConcepts:
    name: mainConcepts
